# Generated by Django 3.2 on 2021-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
