# Generated by Django 3.2 on 2021-04-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_seat_seat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
