# Generated by Django 3.2 on 2021-04-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210425_2328'),
        ('booking', '0005_booking_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Screen',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
