# Generated by Django 3.2 on 2021-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=20, verbose_name='Movie Name')),
                ('poster', models.ImageField(null=True, upload_to='%Y/%m/%d/')),
                ('ticket_price', models.FloatField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('screen', models.ManyToManyField(to='booking.Screen')),
            ],
        ),
    ]
