# Generated by Django 3.2 on 2021-04-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
