# Generated by Django 3.2 on 2021-04-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210425_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.AddField(
            model_name='seat',
            name='show',
            field=models.ManyToManyField(to='movie.Show'),
        ),
    ]
